name: Flutter CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ios_build:
    name: Build iOS
    runs-on: macos-latest
    env:
      XCODE_WORKSPACE: "ios/Runner.xcworkspace"
      XCODE_SCHEME: Runner
      BUILD_CONFIGURATION: Release
      TEAM_ID: 4G27BQU73C
    steps:
      - uses: actions/checkout@v2

      - name: Install python and codemagic tools
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: python -m pip install codemagic-cli-tools

      - name: Decode and install certificate and profile
        run: |
          echo ${{ secrets.IOS_CERTIFICATE }} | base64 --decode > ${HOME}/certificate.p12
          echo ${{ secrets.IOS_PROVISIONING_PROFILE }} | base64 --decode > ${HOME}/profile.mobileprovision
          security create-keychain -p "" build.keychain
          security import ${HOME}/certificate.p12 -k build.keychain -P ${{ secrets.CERT_PASSWORD }} -T /usr/bin/codesign
          security set-keychain-settings -t 3600 -u build.keychain
          security unlock-keychain -p "" build.keychain
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ${HOME}/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Set up code signing settings on Xcode project
        run: xcode-project use-profiles

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.2'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build and version iOS app
        run: |
          flutter build ipa --release \
            --export-options-plist=/Users/runner/export_options.plist

      - name: Upload to Pgyer
        run: curl -F "file=@${{ github.workspace }}/build/ios/iphoneos/Runner.ipa" -F "_api_key=${{ secrets.PGYER_API_KEY }}" https://www.pgyer.com/apiv2/app/upload

  android_build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.2'
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --verbose
      - name: Upload to Pgyer
        run: curl -F "file=@${{ github.workspace }}/build/app/outputs/flutter-apk/app-release.apk" -F "_api_key=${{ secrets.PGYER_API_KEY }}" https://www.pgyer.com/apiv2/app/upload
