name: Flutter_CI

on:
  push:
    branches: [main] # 触发条件：当主分支有代码推送时
  pull_request:
    branches: [main] # 触发条件：当主分支有pull request时

jobs:
  build-and-sign-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.2' # 替换为你使用的Flutter版本

      - name: Install python and codemagic tools
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
  
      - name: Install python dependencies
        run: python -m pip install codemagic-cli-tools

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
            p12-file-base64: ${{ secrets.IOS_CERTIFICATE }}
            p12-password: ${{ secrets.CERT_PASSWORD }}

      - name: Install the provisioning profile
        env:
            PROVISIONING_CERTIFICATE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE }}
        run: |
            PP_PATH=$HOME/profile.mobileprovision
            echo -n "$PROVISIONING_CERTIFICATE_BASE64" | base64 --decode --output $PP_PATH
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
        
      - name: Check Certificates in Keychain
        run: security list-keychains

      - name: Set up code signing settings on Xcode project
        run: xcode-project use-profiles

      - name: Install dependencies
        run: flutter pub get
        
      - name: Run tests
        run: flutter test

      - name: Build and version iOS app
        run: |
          flutter build ipa --release \
            --export-options-plist=/Users/runner/export_options.plist

      - name: Upload to Pgyer
        run: curl -F "file=@${{ github.workspace }}/build/ios/iphoneos/Runner.ipa" -F "_api_key=${{ secrets.PGYER_API_KEY }}" https://www.pgyer.com/apiv2/app/upload
    
  android_build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.2'
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --verbose
      - name: Upload to Pgyer
        run: curl -F "file=@${{ github.workspace }}/build/app/outputs/flutter-apk/app-release.apk" -F "_api_key=${{ secrets.PGYER_API_KEY }}" https://www.pgyer.com/apiv2/app/upload
