name: Flutter_CI

on:
  push:
    branches: [main] # 触发条件：当主分支有代码推送时
  pull_request:
    branches: [main] # 触发条件：当主分支有pull request时

jobs:
  build-and-sign-ios:
    runs-on: macos-latest
    env:
      PACKAGE_NAME: flutteryaml.ipa  # 定义包名作为一个环境变量

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.2' # 替换为你使用的Flutter版本

      - name: Install python and codemagic tools
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
  
      - name: Install python dependencies
        run: python -m pip install codemagic-cli-tools

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
            p12-file-base64: ${{ secrets.IOS_CERTIFICATE }}
            p12-password: ${{ secrets.CERT_PASSWORD }}

      - name: Install the provisioning profile
        env:
            PROVISIONING_CERTIFICATE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE }}
        run: |
            PP_PATH=$HOME/profile.mobileprovision
            echo -n "$PROVISIONING_CERTIFICATE_BASE64" | base64 --decode --output $PP_PATH
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
        
      - name: Check Certificates in Keychain
        run: security list-keychains

      - name: Set up code signing settings on Xcode project
        run: xcode-project use-profiles

      - name: Install dependencies
        run: flutter pub get
        
      - name: Run tests
        run: flutter test

      - name: Build and version iOS app
        run: |
          flutter build ipa --release \
            --export-options-plist=/Users/runner/export_options.plist

      # - name: List IPA file
      #   run: ls -lR /Users/runner/work/flutter-android-and-ios-yaml-demo-project/flutter-android-and-ios-yaml-demo-project/build/ios/
 
      - name: Upload to Pgyer
        run: curl -F "file=@${{ github.workspace }}/build/ios/ipa/${{ env.PACKAGE_NAME }}" -F "_api_key=${{ secrets.PGYER_API_KEY }}" https://www.pgyer.com/apiv2/app/upload
     
      - name: Publish iOS Artefacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ github.workspace }}/build/ios/ipa/
    
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Java to compile Android project
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.2"

      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          # import keystore from secrets
          ls -all
          echo $KEYSTORE_BASE64 | base64 -di > android/app/key.jks

      - name: Restore packages
        run: flutter pub get

      - name: Build Android App Bundle
        run: flutter build apk --release
        
      - name: Upload to Pgyer
        run: curl -F "file=@${{ github.workspace }}/build/app/outputs/flutter-apk/app-release.apk" -F "_api_key=${{ secrets.PGYER_API_KEY }}" https://www.pgyer.com/apiv2/app/upload

      - name: Publish Android Artefacts
        uses: actions/upload-artifact@v1
        with:
          name: release-aab
          path: build/app/outputs/apk/release/app-release.apk
